name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Install .NET Framework 4.0 Developer Pack
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe -OutFile dotNetFx40_Full_x86_x64.exe
        Start-Process -FilePath .\dotNetFx40_Full_x86_x64.exe -ArgumentList '/q /norestart' -Wait

    - name: Build solution
      run: msbuild DNSLookup.sln /p:Configuration=Release

    - name: Run tests
      run: Tools/NUnit/nunit.exe nDNS.Tests/bin/Release/CodeMangler.nDNS.Tests.dll
