name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Build solution
      run: |
        dotnet restore DNSLookup.sln
        dotnet build DNSLookup.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test DNSLookup.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory TestResults

    - name: Upload Test Results
      if: always() # Ensure this runs even if tests fail, to upload partial results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/**/*.trx

    - name: Upload Code Coverage Report
      if: always() # Ensure this runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: '**/*.cobertura.xml'
        # The glob pattern will search for cobertura.xml files in any directory.
        # Coverlet usually outputs them within the test project directories.
